// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package agent

import (
	"context"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type JobRunReq struct {
	g.Meta `path:"/agent/job/{id}/run" tags:"job run" method:"get" summary:"JobRunReq"`
}
type JobAbortReq struct {
	g.Meta `path:"/agent/job/{id}/abort" tags:"job run" method:"get" summary:"JobAbortReq"`
}

type IAgentV1 interface {
	JobRun(ctx context.Context, req *JobRunReq) (res *ghttp.Response, err error)
	JobAbort(ctx context.Context, req *JobAbortReq) (res *ghttp.Response, err error)
}

type ControllerV1 struct{}

func NewV1() IAgentV1 {
	return &ControllerV1{}
}
