// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package agent

import (
	"context"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type AgentReq struct {
	g.Meta `path:"/agent" tags:"agent" method:"get" summary:"UiReq"`
}

type IAgentV1 interface {
	Agent(ctx context.Context, req *AgentReq) (res *ghttp.Response, err error)
}

type ControllerV1 struct{}

func NewV1() IAgentV1 {
	return &ControllerV1{}
}
