# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:mypassword@tcp(127.0.0.1:3306)/gojob"
        descriptionTag: true
        tables: "cicd_user,cicd_group,cicd_agent,cicd_pipeline,cicd_script,cicd_job,cicd_log"

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
