// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gojob/internal/dao/internal"
)

// internalCicdScriptDao is an internal type for wrapping the internal DAO implementation.
type internalCicdScriptDao = *internal.CicdScriptDao

// cicdScriptDao is the data access object for the table cicd_script.
// You can define custom methods on it to extend its functionality as needed.
type cicdScriptDao struct {
	internalCicdScriptDao
}

var (
	// CicdScript is a globally accessible object for table cicd_script operations.
	CicdScript = cicdScriptDao{
		internal.NewCicdScriptDao(),
	}
)

// Add your custom methods and functionality below.
