// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gojob/internal/dao/internal"
)

// internalCicdLogDao is an internal type for wrapping the internal DAO implementation.
type internalCicdLogDao = *internal.CicdLogDao

// cicdLogDao is the data access object for the table cicd_log.
// You can define custom methods on it to extend its functionality as needed.
type cicdLogDao struct {
	internalCicdLogDao
}

var (
	// CicdLog is a globally accessible object for table cicd_log operations.
	CicdLog = cicdLogDao{
		internal.NewCicdLogDao(),
	}
)

// Add your custom methods and functionality below.
