// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gojob/internal/dao/internal"
)

// internalCicdPipelineDao is an internal type for wrapping the internal DAO implementation.
type internalCicdPipelineDao = *internal.CicdPipelineDao

// cicdPipelineDao is the data access object for the table cicd_pipeline.
// You can define custom methods on it to extend its functionality as needed.
type cicdPipelineDao struct {
	internalCicdPipelineDao
}

var (
	// CicdPipeline is a globally accessible object for table cicd_pipeline operations.
	CicdPipeline = cicdPipelineDao{
		internal.NewCicdPipelineDao(),
	}
)

// Add your custom methods and functionality below.
