// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gojob/internal/dao/internal"
)

// internalCicdAgentDao is an internal type for wrapping the internal DAO implementation.
type internalCicdAgentDao = *internal.CicdAgentDao

// cicdAgentDao is the data access object for the table cicd_agent.
// You can define custom methods on it to extend its functionality as needed.
type cicdAgentDao struct {
	internalCicdAgentDao
}

var (
	// CicdAgent is a globally accessible object for table cicd_agent operations.
	CicdAgent = cicdAgentDao{
		internal.NewCicdAgentDao(),
	}
)

// Add your custom methods and functionality below.
