// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gojob/internal/dao/internal"
)

// internalCicdUserDao is an internal type for wrapping the internal DAO implementation.
type internalCicdUserDao = *internal.CicdUserDao

// cicdUserDao is the data access object for the table cicd_user.
// You can define custom methods on it to extend its functionality as needed.
type cicdUserDao struct {
	internalCicdUserDao
}

var (
	// CicdUser is a globally accessible object for table cicd_user operations.
	CicdUser = cicdUserDao{
		internal.NewCicdUserDao(),
	}
)

// Add your custom methods and functionality below.
