// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gojob/internal/dao/internal"
)

// internalCicdGroupDao is an internal type for wrapping the internal DAO implementation.
type internalCicdGroupDao = *internal.CicdGroupDao

// cicdGroupDao is the data access object for the table cicd_group.
// You can define custom methods on it to extend its functionality as needed.
type cicdGroupDao struct {
	internalCicdGroupDao
}

var (
	// CicdGroup is a globally accessible object for table cicd_group operations.
	CicdGroup = cicdGroupDao{
		internal.NewCicdGroupDao(),
	}
)

// Add your custom methods and functionality below.
