// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package ui

import (
	"context"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type UiReq struct {
	g.Meta `path:"/ui" tags:"ui" method:"get" summary:"UiReq"`
}

// auth
type AuthLoginReq struct {
	g.Meta `path:"/login" tags:"ui" method:"get" summary:"AuthLoginReq"`
}
type AuthCallbackReq struct {
	g.Meta `path:"/callback" tags:"ui" method:"get" summary:"AuthCallbackReq"`
}
type AuthLogoutReq struct {
	g.Meta `path:"/logout" tags:"ui" method:"get" summary:"AuthLogoutReq"`
}

// groups
type GroupGetListReq struct {
	g.Meta `path:"/groups" tags:"ui" method:"get" summary:"GroupGetListReq"`
}
type GroupNewReq struct {
	g.Meta `path:"/groupnew" tags:"ui" method:"get" summary:"GroupNewReq"`
}
type GroupCreateReq struct {
	g.Meta `path:"/groups" tags:"ui" method:"post" summary:"GroupCreateReq"`
}
type GroupGetOneReq struct {
	g.Meta `path:"/groups/{id}" tags:"ui" method:"get" summary:"GroupGetOneReq"`
}
type GroupUpdateReq struct {
	g.Meta `path:"/groups/{id}/put" tags:"ui" method:"post" summary:"GroupUpdateReq"`
}

// users
type UserGetListReq struct {
	g.Meta `path:"/users" tags:"ui" method:"get" summary:"UserGetListReq"`
}
type UserNewReq struct {
	g.Meta `path:"/usernew" tags:"ui" method:"get" summary:"UserNewReq"`
}
type UserCreateReq struct {
	g.Meta `path:"/users" tags:"ui" method:"post" summary:"UserCreateReq"`
}
type UserGetOneReq struct {
	g.Meta `path:"/users/{id}" tags:"ui" method:"get" summary:"UserGetOneReq"`
}
type UserUpdateReq struct {
	g.Meta `path:"/users/{id}/put" tags:"ui" method:"post" summary:"UserUpdateReq"`
}

// agents
type AgentGetListReq struct {
	g.Meta `path:"/agents" tags:"ui" method:"get" summary:"AgentGetListReq"`
}
type AgentNewReq struct {
	g.Meta `path:"/agentnew" tags:"ui" method:"get" summary:"AgentNewReq"`
}
type AgentCreateReq struct {
	g.Meta `path:"/agents" tags:"ui" method:"post" summary:"AgentCreateReq"`
}
type AgentGetOneReq struct {
	g.Meta `path:"/agents/{id}" tags:"ui" method:"get" summary:"AgentGetOneReq"`
}
type AgentUpdateReq struct {
	g.Meta `path:"/agents/{id}/put" tags:"ui" method:"post" summary:"AgentUpdateReq"`
}

// scripts
type ScriptGetListReq struct {
	g.Meta `path:"/scripts" tags:"ui" method:"get" summary:"ScriptGetListReq"`
}
type ScriptNewReq struct {
	g.Meta `path:"/scriptnew" tags:"ui" method:"get" summary:"ScriptNewReq"`
}
type ScriptCreateReq struct {
	g.Meta `path:"/scripts" tags:"ui" method:"post" summary:"ScriptCreateReq"`
}
type ScriptGetOneReq struct {
	g.Meta `path:"/scripts/{id}" tags:"ui" method:"get" summary:"ScriptGetOneReq"`
}
type ScriptUpdateReq struct {
	g.Meta `path:"/scripts/{id}/put" tags:"ui" method:"post" summary:"ScriptUpdateReq"`
}

// pipelines
type PipelineGetListReq struct {
	g.Meta `path:"/pipelines" tags:"ui" method:"get" summary:"PipelineGetListReq"`
}
type PipelineNewReq struct {
	g.Meta `path:"/pipelinenew" tags:"ui" method:"get" summary:"PipelineNewReq"`
}
type PipelineCreateReq struct {
	g.Meta `path:"/pipelines" tags:"ui" method:"post" summary:"PipelineCreateReq"`
}
type PipelineGetOneReq struct {
	g.Meta `path:"/pipelines/{id}" tags:"ui" method:"get" summary:"PipelineGetOneReq"`
}
type PipelineUpdateReq struct {
	g.Meta `path:"/pipelines/{id}/put" tags:"ui" method:"post" summary:"PipelineUpdateReq"`
}

// cicd/jobs/tasks
type CicdGetListReq struct {
	g.Meta `path:"/" tags:"ui" method:"get" summary:"CicdGetListReq"`
}
type CicdGetOneReq struct {
	g.Meta `path:"/jobs/{id}" tags:"ui" method:"get" summary:"CicdGetOneReq"`
}
type CicdBodyGetOneReq struct {
	g.Meta `path:"/jobs/{id}/body" tags:"ui" method:"get" summary:"CicdBodyGetOneReq"`
}
type CicdJobCreateReq struct {
	g.Meta `path:"/jobs/{pipeline_id}/newjob" tags:"ui" method:"post" summary:"CicdJobCreateReq"`
}
type CicdJobGetOneReq struct {
	g.Meta `path:"/jobs/{pipeline_id}/{job_id}" tags:"ui" method:"get" summary:"CicdJobGetOneReq"`
}
type CicdLogGetOneReq struct {
	g.Meta `path:"/jobs/{pipeline_id}/{task_id}/log2" tags:"ui" method:"get" summary:"CicdLogGetOneReq"`
}
type JobLogGetOneReq struct {
	g.Meta `path:"/jobs/{pipeline_id}/{job_id}/log" tags:"ui" method:"get" summary:"JobLogGetOneReq"`
}

// type CicdGetListPkgsReq struct {
// 	g.Meta `path:"/{id}/pkgs" tags:"ui" method:"get" summary:"CicdGetListPkgsReq"`
// }

type IUiV1 interface {
	Ui(ctx context.Context, req *UiReq) (res *ghttp.Response, err error)

	AuthLogin(ctx context.Context, req *AuthLoginReq) (res *ghttp.Response, err error)
	AuthCallback(ctx context.Context, req *AuthCallbackReq) (res *ghttp.Response, err error)
	AuthLogout(ctx context.Context, req *AuthLogoutReq) (res *ghttp.Response, err error)

	GroupGetList(ctx context.Context, req *GroupGetListReq) (res *ghttp.Response, err error)
	GroupNew(ctx context.Context, req *GroupNewReq) (res *ghttp.Response, err error)
	GroupCreate(ctx context.Context, req *GroupCreateReq) (res *ghttp.Response, err error)
	GroupGetOne(ctx context.Context, req *GroupGetOneReq) (res *ghttp.Response, err error)
	GroupUpdate(ctx context.Context, req *GroupUpdateReq) (res *ghttp.Response, err error)

	UserGetList(ctx context.Context, req *UserGetListReq) (res *ghttp.Response, err error)
	UserNew(ctx context.Context, req *UserNewReq) (res *ghttp.Response, err error)
	UserCreate(ctx context.Context, req *UserCreateReq) (res *ghttp.Response, err error)
	UserGetOne(ctx context.Context, req *UserGetOneReq) (res *ghttp.Response, err error)
	UserUpdate(ctx context.Context, req *UserUpdateReq) (res *ghttp.Response, err error)

	AgentGetList(ctx context.Context, req *AgentGetListReq) (res *ghttp.Response, err error)
	AgentNew(ctx context.Context, req *AgentNewReq) (res *ghttp.Response, err error)
	AgentCreate(ctx context.Context, req *AgentCreateReq) (res *ghttp.Response, err error)
	AgentGetOne(ctx context.Context, req *AgentGetOneReq) (res *ghttp.Response, err error)
	AgentUpdate(ctx context.Context, req *AgentUpdateReq) (res *ghttp.Response, err error)

	ScriptGetList(ctx context.Context, req *ScriptGetListReq) (res *ghttp.Response, err error)
	ScriptNew(ctx context.Context, req *ScriptNewReq) (res *ghttp.Response, err error)
	ScriptCreate(ctx context.Context, req *ScriptCreateReq) (res *ghttp.Response, err error)
	ScriptGetOne(ctx context.Context, req *ScriptGetOneReq) (res *ghttp.Response, err error)
	ScriptUpdate(ctx context.Context, req *ScriptUpdateReq) (res *ghttp.Response, err error)

	PipelineGetList(ctx context.Context, req *PipelineGetListReq) (res *ghttp.Response, err error)
	PipelineNew(ctx context.Context, req *PipelineNewReq) (res *ghttp.Response, err error)
	PipelineCreate(ctx context.Context, req *PipelineCreateReq) (res *ghttp.Response, err error)
	PipelineGetOne(ctx context.Context, req *PipelineGetOneReq) (res *ghttp.Response, err error)
	PipelineUpdate(ctx context.Context, req *PipelineUpdateReq) (res *ghttp.Response, err error)

	CicdGetList(ctx context.Context, req *CicdGetListReq) (res *ghttp.Response, err error)
	CicdGetOne(ctx context.Context, req *CicdGetOneReq) (res *ghttp.Response, err error)
	CicdBodyGetOne(ctx context.Context, req *CicdBodyGetOneReq) (res *ghttp.Response, err error)
	// CicdGetListPkgs(ctx context.Context, req *CicdGetListPkgsReq) (res *ghttp.Response, err error)
	CicdJobCreate(ctx context.Context, req *CicdJobCreateReq) (res *ghttp.Response, err error)
	CicdJobGetOne(ctx context.Context, req *CicdJobGetOneReq) (res *ghttp.Response, err error)
	CicdLogGetOne(ctx context.Context, req *CicdLogGetOneReq) (res *ghttp.Response, err error)
}

type ControllerV1 struct{}

func NewV1() IUiV1 {
	return &ControllerV1{}
}
